name = "email-site-logos"
type = "javascript"
main = "src/index.js"
compatibility_date = "2025-04-18"

[vars]
CLIENT_ID = "21b3d17673984abf86ad76aaba6cc371"
CLIENT_SECRET = "528c8261e0755be29840f9bc06070fa6"